/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Airdrop } from "./Airdrop";
export type { IMintableERC20 } from "./IMintableERC20";
export type { PolygonIdMinter } from "./PolygonIdMinter";
export * as factories from "./factories";
export { Airdrop__factory } from "./factories/Airdrop__factory";
export { IMintableERC20__factory } from "./factories/IMintableERC20__factory";
export { PolygonIdMinter__factory } from "./factories/PolygonIdMinter__factory";
