/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Verifier } from "./ERC20Verifier";
export * as factories from "./factories";
export { ERC20Verifier__factory } from "./factories/ERC20Verifier__factory";
